import { Link } from "../../../global-types";

export const tempPosts: Link[] = [
	{
		id: "1",
		name: "t3_1",
		kind: "t3",
		author: "u/bigabear",
		ups: 500,
		downs: 0,
		created: 182747958,
		author_flair_text: "https://i.imgur.com/3ZQcX3P.png",
		author_flair_css_class: null,
		clicked: false,
		domain: "i.imgur.com",
		hidden: false,
		is_self: false,
		likes: null,
		link_flair_css_class: null,
		link_flair_text: null,
		locked: false,
		media: null,
		media_embed: {},
		num_comments: 0,
		over_18: false,
		permalink: "google.com",
		saved: false,
		score: 0,
		selftext: "",
		selftext_html:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magnaaliqua. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Aliquam eleifend mi in nulla posuere.Sed egestas egestas fringilla phasellus faucibus scelerisque. Neque sodales ut etiam sit amet nisl purus in mollis. Eget mauris pharetra ultrice Purus gravida quis blandit turpis cursus in. Risus viverra adipiscing at in tellus. Nec ultrices dui sapien eget mi. Felis eget nunc lobortis mattis aliquam faucibus purus in massa.",
		subreddit: "pics",
		subreddit_id: "t5_2qh0u",
		thumbnail: "https://b",
		title: "This is a test post",
		url: "https://i.imgur.com/3ZQcX3P.png",
		edited: false,
		distinguished: null,
		stickied: false,
	},
	{
		id: "2",
		name: "t3_1",
		kind: "t3",
		author: "u/bigabear",
		ups: 1,
		downs: 0,
		created: 182747958,
		author_flair_text: "https://i.imgur.com/3ZQcX3P.png",
		author_flair_css_class: null,
		clicked: false,
		domain: "i.imgur.com",
		hidden: false,
		is_self: false,
		likes: true,
		link_flair_css_class: null,
		link_flair_text: null,
		locked: false,
		media: null,
		media_embed: {},
		num_comments: 0,
		over_18: false,
		permalink: "google.com",
		saved: false,
		score: 0,
		selftext: "",
		selftext_html:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magnaaliqua. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Aliquam eleifend mi in nulla posuere.Sed egestas egestas fringilla phasellus faucibus scelerisque. Neque sodales ut etiam sit amet nisl purus in mollis. Eget mauris pharetra ultrice Purus gravida quis blandit turpis cursus in. Risus viverra adipiscing at in tellus. Nec ultrices dui sapien eget mi. Felis eget nunc lobortis mattis aliquam faucibus purus in massa.",
		subreddit: "pics",
		subreddit_id: "t5_2qh0u",
		thumbnail: "https://b",
		title: "This is a test post",
		url: "https://i.imgur.com/3ZQcX3P.png",
		edited: false,
		distinguished: null,
		stickied: false,
	},
	{
		id: "3",
		name: "t3_1",
		kind: "t3",
		author: "u/bigabear",
		ups: 0,
		downs: 0,
		created: 182747958,
		author_flair_text: "https://i.imgur.com/3ZQcX3P.png",
		author_flair_css_class: null,
		clicked: false,
		domain: "i.imgur.com",
		hidden: false,
		is_self: false,
		likes: null,
		link_flair_css_class: null,
		link_flair_text: null,
		locked: false,
		media: null,
		media_embed: {},
		num_comments: 0,
		over_18: false,
		permalink: "google.com",
		saved: false,
		score: 0,
		selftext: "",
		selftext_html:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magnaaliqua. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Aliquam eleifend mi in nulla posuere.Sed egestas egestas fringilla phasellus faucibus scelerisque. Neque sodales ut etiam sit amet nisl purus in mollis. Eget mauris pharetra ultrice Purus gravida quis blandit turpis cursus in. Risus viverra adipiscing at in tellus. Nec ultrices dui sapien eget mi. Felis eget nunc lobortis mattis aliquam faucibus purus in massa.",
		subreddit: "pics",
		subreddit_id: "t5_2qh0u",
		thumbnail: "https://b",
		title: "This is a test post",
		url: "https://i.imgur.com/3ZQcX3P.png",
		edited: false,
		distinguished: null,
		stickied: false,
	},
];
